/**
 * Script para popular a base RAG com documentos pedagógicos oficiais.
 * Executar uma vez: node --env-file=.env src/nexus7/rag-seed.js
 *
 * Popula: BNCC (habilidades por área/série), LDB (artigos relevantes),
 * Lei 13.146/2015 (artigos de inclusão), DSM-5/CID-11 (perfis de NEE),
 * Decretos e Resoluções do MEC.
 */
import { indexDocumentsBatch } from "./rag.service.js";

const BNCC_MATEMATICA = [
  { title: "EF01MA01", content: "Utilizar números naturais como indicador de quantidade ou de ordem em diferentes situações cotidianas e reconhecer situações em que os números não indicam contagem nem ordem, mas sim código de identificação.", metadata: { area: "Matemática", serie: "1º ano", componente: "MA" } },
  { title: "EF01MA02", content: "Contar de maneira exata ou aproximada, utilizando diferentes estratégias como o pareamento e outros agrupamentos.", metadata: { area: "Matemática", serie: "1º ano", componente: "MA" } },
  { title: "EF01MA03", content: "Estimar e comparar quantidades de objetos de dois conjuntos (em torno de 20 elementos), por estimativa e/ou por correspondência (um a um, dois a dois) para indicar 'tem mais', 'tem menos' ou 'tem a mesma quantidade'.", metadata: { area: "Matemática", serie: "1º ano", componente: "MA" } },
  { title: "EF01MA04", content: "Contar a quantidade de objetos de coleções até 100 unidades e apresentar o resultado por registros verbais e simbólicos, em situações de seu interesse, como jogos, brincadeiras, materiais da sala de aula, entre outros.", metadata: { area: "Matemática", serie: "1º ano", componente: "MA" } },
  { title: "EF01MA05", content: "Comparar números naturais de até duas ordens em situações cotidianas, com e sem suporte da reta numérica.", metadata: { area: "Matemática", serie: "1º ano", componente: "MA" } },
  { title: "EF02MA01", content: "Comparar e ordenar números naturais (até a ordem de centenas) pela compreensão de características do sistema de numeração decimal (valor posicional e função do zero).", metadata: { area: "Matemática", serie: "2º ano", componente: "MA" } },
  { title: "EF02MA05", content: "Construir fatos básicos da adição e utilizá-los em procedimentos de cálculo para resolver problemas.", metadata: { area: "Matemática", serie: "2º ano", componente: "MA" } },
  { title: "EF03MA01", content: "Ler, escrever e comparar números naturais de até a ordem de unidade de milhar, estabelecendo relações entre os registros numéricos e em língua materna.", metadata: { area: "Matemática", serie: "3º ano", componente: "MA" } },
  { title: "EF04MA01", content: "Ler, escrever e ordenar números naturais até a ordem de dezenas de milhar.", metadata: { area: "Matemática", serie: "4º ano", componente: "MA" } },
  { title: "EF05MA01", content: "Ler, escrever e ordenar números naturais até a ordem das centenas de milhar com compreensão das principais características do sistema de numeração decimal.", metadata: { area: "Matemática", serie: "5º ano", componente: "MA" } },
  { title: "EF05MA03", content: "Identificar e representar frações (menores e maiores que a unidade), associando-as ao resultado de uma divisão ou à ideia de parte de um todo, utilizando a reta numérica como recurso.", metadata: { area: "Matemática", serie: "5º ano", componente: "MA" } },
  { title: "EF06MA01", content: "Comparar, ordenar, ler e escrever números naturais e números racionais cuja representação decimal é finita, fazendo uso da reta numérica.", metadata: { area: "Matemática", serie: "6º ano", componente: "MA" } },
  { title: "EF07MA01", content: "Resolver e elaborar problemas com números naturais, envolvendo as noções de divisor e de múltiplo, podendo incluir máximo divisor comum ou mínimo múltiplo comum, por meio de estratégias diversas, sem a aplicação de algoritmos.", metadata: { area: "Matemática", serie: "7º ano", componente: "MA" } },
  { title: "EF07MA04", content: "Resolver e elaborar problemas que envolvam operações com números inteiros.", metadata: { area: "Matemática", serie: "7º ano", componente: "MA" } },
  { title: "EF08MA01", content: "Efetuar cálculos com potências de expoentes inteiros e aplicar esse conhecimento na representação de números em notação científica.", metadata: { area: "Matemática", serie: "8º ano", componente: "MA" } },
  { title: "EF09MA01", content: "Reconhecer que, uma vez fixada uma unidade de comprimento, existem segmentos de reta cujo comprimento não é expresso por número racional (como a medida da diagonal de um quadrado de lado unitário).", metadata: { area: "Matemática", serie: "9º ano", componente: "MA" } },
];

const BNCC_CIENCIAS = [
  { title: "EF01CI01", content: "Comparar características de diferentes materiais presentes em objetos de uso cotidiano, discutindo sua origem, os modos como são descartados e como podem ser usados de forma mais consciente.", metadata: { area: "Ciências", serie: "1º ano", componente: "CI" } },
  { title: "EF02CI01", content: "Identificar de que materiais (metais, madeira, vidro etc.) são feitos os objetos que fazem parte da vida cotidiana, como esses objetos são utilizados e com quais materiais eram produzidos no passado.", metadata: { area: "Ciências", serie: "2º ano", componente: "CI" } },
  { title: "EF03CI01", content: "Produzir diferentes sons a partir da vibração de variados objetos e identificar variáveis que influem nesse fenômeno.", metadata: { area: "Ciências", serie: "3º ano", componente: "CI" } },
  { title: "EF04CI01", content: "Identificar misturas na vida diária, com base em suas propriedades físicas observáveis, reconhecendo sua composição.", metadata: { area: "Ciências", serie: "4º ano", componente: "CI" } },
  { title: "EF05CI01", content: "Explorar fenômenos da vida cotidiana que evidenciem propriedades físicas dos materiais – como densidade, condutibilidade térmica e elétrica, respostas a forças magnéticas, solubilidade, respostas a forças mecânicas (dureza, elasticidade etc.).", metadata: { area: "Ciências", serie: "5º ano", componente: "CI" } },
  { title: "EF06CI01", content: "Classificar como homogênea ou heterogênea a mistura de dois ou mais materiais (água e sal, água e óleo, água e areia etc.).", metadata: { area: "Ciências", serie: "6º ano", componente: "CI" } },
  { title: "EF07CI01", content: "Discutir a aplicação, ao longo da história, das máquinas simples e propor soluções e invenções para a realização de tarefas mecânicas cotidianas.", metadata: { area: "Ciências", serie: "7º ano", componente: "CI" } },
  { title: "EF07CI08", content: "Avaliar como os impactos provocados por catástrofes naturais ou mudanças nos componentes físicos, biológicos ou sociais de um ecossistema afetam suas populações, podendo ameaçar ou provocar a extinção de espécies, alteração de hábitos, migração etc.", metadata: { area: "Ciências", serie: "7º ano", componente: "CI" } },
  { title: "EF08CI01", content: "Identificar e classificar diferentes fontes (renováveis e não renováveis) e tipos de energia utilizados em residências, comunidades ou cidades.", metadata: { area: "Ciências", serie: "8º ano", componente: "CI" } },
  { title: "EF09CI01", content: "Investigar as mudanças de estado físico da matéria e explicar essas transformações com base no modelo de constituição submicroscópica.", metadata: { area: "Ciências", serie: "9º ano", componente: "CI" } },
];

const BNCC_LINGUA_PORTUGUESA = [
  { title: "EF01LP01", content: "Reconhecer que textos são lidos e escritos da esquerda para a direita e de cima para baixo da página.", metadata: { area: "Língua Portuguesa", serie: "1º ano", componente: "LP" } },
  { title: "EF01LP02", content: "Escrever, espontaneamente ou por ditado, palavras e frases de forma alfabética – usando letras/grafemas que representem fonemas.", metadata: { area: "Língua Portuguesa", serie: "1º ano", componente: "LP" } },
  { title: "EF02LP01", content: "Utilizar, ao produzir o texto, grafia correta de palavras conhecidas ou com estruturas silábicas já dominadas, letras maiúsculas em início de frases e em substantivos próprios, segmentação entre as palavras, ponto final, ponto de interrogação e ponto de exclamação.", metadata: { area: "Língua Portuguesa", serie: "2º ano", componente: "LP" } },
  { title: "EF03LP01", content: "Ler e escrever palavras com correspondências regulares contextuais entre grafemas e fonemas.", metadata: { area: "Língua Portuguesa", serie: "3º ano", componente: "LP" } },
  { title: "EF05LP01", content: "Grafar palavras utilizando regras de correspondência fonema-grafema regulares, contextuais e morfológicas e palavras de uso frequente com correspondências irregulares.", metadata: { area: "Língua Portuguesa", serie: "5º ano", componente: "LP" } },
  { title: "EF06LP01", content: "Reconhecer a impossibilidade de uma tradução palavra por palavra de textos escritos em língua estrangeira para a língua portuguesa, comparando estruturas linguísticas e observando as diferenças entre elas.", metadata: { area: "Língua Portuguesa", serie: "6º ano", componente: "LP" } },
  { title: "EF07LP01", content: "Distinguir diferentes propostas editoriais – Loss de divulgação científica, jornais, revistas, blogs etc. –, de forma a identificar os recursos linguísticos e gráficos utilizados nesses gêneros textuais.", metadata: { area: "Língua Portuguesa", serie: "7º ano", componente: "LP" } },
  { title: "EF09LP01", content: "Analisar o fenômeno da disseminação de notícias falsas nas redes sociais e desenvolver estratégias para reconhecê-las, a partir da verificação/avaliação do veículo, currentIndexor, data de publicação e adequação entre manchete e corpo da notícia.", metadata: { area: "Língua Portuguesa", serie: "9º ano", componente: "LP" } },
];

const LEGISLACAO = [
  { source: "LDB", category: "artigo", title: "LDB Art. 58", content: "Entende-se por educação especial, para os efeitos desta Lei, a modalidade de educação escolar oferecida preferencialmente na rede regular de ensino, para educandos com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação. § 1º Haverá, quando necessário, serviços de apoio especializado, na escola regular, para atender às peculiaridades da clientela de educação especial. § 2º O atendimento educacional será feito em classes, escolas ou serviços especializados, sempre que, em função das condições específicas dos alunos, não for possível a sua integração nas classes comuns de ensino regular. § 3º A oferta de educação especial, nos termos do caput deste artigo, tem início na educação infantil e estende-se ao longo da vida." },
  { source: "LDB", category: "artigo", title: "LDB Art. 59", content: "Os sistemas de ensino assegurarão aos educandos com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação: I – currículos, métodos, técnicas, recursos educativos e organização específicos, para atender às suas necessidades; II – terminalidade específica para aqueles que não puderem atingir o nível exigido para a conclusão do ensino fundamental, em virtude de suas deficiências; III – professores com especialização adequada em nível médio ou superior; IV – educação especial para o trabalho; V – acesso igualitário aos benefícios dos programas sociais suplementares." },
  { source: "LDB", category: "artigo", title: "LDB Art. 60", content: "Os órgãos normativos dos sistemas de ensino estabelecerão critérios de caracterização das instituições privadas sem fins lucrativos, especializadas e com atuação exclusiva em educação especial, para fins de apoio técnico e financeiro pelo Poder Público." },
  { source: "Lei_13146", category: "artigo", title: "Lei 13.146/2015 Art. 27", content: "A educação constitui direito da pessoa com deficiência, assegurados sistema educacional inclusivo em todos os níveis e aprendizado ao longo de toda a vida, de forma a alcançar o máximo desenvolvimento possível de seus talentos e habilidades físicas, sensoriais, intelectuais e sociais, segundo suas características, interesses e necessidades de aprendizagem." },
  { source: "Lei_13146", category: "artigo", title: "Lei 13.146/2015 Art. 28", content: "Incumbe ao poder público assegurar, criar, desenvolver, implementar, incentivar, acompanhar e avaliar: I – sistema educacional inclusivo em todos os níveis e modalidades; II – aprimoramento dos sistemas educacionais; III – projeto pedagógico que institucionalize o atendimento educacional especializado; IV – oferta de educação bilíngue, em Libras como primeira língua e na modalidade escrita da língua portuguesa como segunda língua; V – adoção de medidas individualizadas e coletivas em ambientes que maximizem o desenvolvimento acadêmico e social dos estudantes com deficiência; VI – pesquisas voltadas para o desenvolvimento de novos métodos e técnicas pedagógicas; VII – planejamento de estudo de caso; VIII – elaboração de plano de atendimento educacional especializado; IX – participação dos estudantes com deficiência e de suas famílias nas diversas instâncias de atuação da comunidade escolar." },
  { source: "Lei_13146", category: "artigo", title: "Lei 13.146/2015 Art. 30", content: "Nos processos seletivos para ingresso e permanência nos cursos oferecidos pelas instituições de ensino superior e de educação profissional e tecnológica, públicas e privadas, devem ser adotadas: I – atendimento preferencial à pessoa com deficiência nas dependências das Instituições de Ensino Superior (IES) e nos serviços; II – disponibilização de formulário de inscrição de exames com campos específicos para que o candidato com deficiência informe os recursos de acessibilidade e de tecnologia assistiva necessários para sua participação; III – disponibilização de provas em formatos acessíveis para atendimento às necessidades específicas do candidato com deficiência; IV – disponibilização de recursos de acessibilidade e de tecnologia assistiva adequados, previamente solicitados e escolhidos pelo candidato com deficiência." },
  { source: "Decreto_7611", category: "artigo", title: "Decreto 7.611/2011 Art. 1º", content: "O dever do Estado com a educação das pessoas público-alvo da educação especial será efetivado de acordo com as seguintes diretrizes: I – garantia de um sistema educacional inclusivo em todos os níveis, sem discriminação e com base na igualdade de oportunidades; II – aprendizado ao longo de toda a vida; III – não exclusão do sistema educacional geral sob alegação de deficiência; IV – garantia de ensino fundamental gratuito e compulsório, asseguradas adaptações razoáveis de acordo com as necessidades individuais; V – oferta de apoio necessário, no âmbito do sistema educacional geral, com vistas a facilitar sua efetiva educação; VI – adoção de medidas de apoio individualizadas e efetivas, em ambientes que maximizem o desenvolvimento acadêmico e social, de acordo com a meta de inclusão plena." },
  { source: "Decreto_7611", category: "artigo", title: "Decreto 7.611/2011 Art. 2º", content: "A educação especial deve garantir os serviços de apoio especializado voltado a eliminar as barreiras que possam obstruir o processo de escolarização de estudantes com deficiência, transtornos globais do desenvolvimento e altas habilidades ou superdotação. § 1º Para fins deste Decreto, os serviços de que trata o caput serão denominados atendimento educacional especializado, compreendido como o conjunto de atividades, recursos de acessibilidade e pedagógicos organizados institucional e continuamente. § 2º O atendimento educacional especializado deve integrar a proposta pedagógica da escola, envolver a participação da família para garantir pleno acesso e participação dos estudantes, atender às necessidades específicas das pessoas público-alvo da educação especial, e ser realizado em articulação com as demais políticas públicas." },
  { source: "Res_CNE_CEB_4_2009", category: "resolucao", title: "Res. CNE/CEB 4/2009 Art. 2º", content: "O AEE tem como função complementar ou suplementar a formação do aluno por meio da disponibilização de serviços, recursos de acessibilidade e estratégias que eliminem as barreiras para sua plena participação na sociedade e desenvolvimento de sua aprendizagem." },
  { source: "Res_CNE_CEB_4_2009", category: "resolucao", title: "Res. CNE/CEB 4/2009 Art. 5º", content: "O AEE é realizado, prioritariamente, na sala de recursos multifuncionais da própria escola ou em outra escola de ensino regular, no turno inverso da escolarização, não sendo substitutivo às classes comuns." },
];

const DSM5_CID11 = [
  { source: "DSM-5", category: "diagnostico", title: "TEA — Transtorno do Espectro Autista (DSM-5 299.00 / CID-11 6A02)", content: "Déficits persistentes na comunicação social e na interação social em múltiplos contextos. Padrões restritos e repetitivos de comportamento, interesses ou atividades. Os sintomas devem estar presentes precocemente no período do desenvolvimento. Níveis de gravidade: Nível 1 (exigindo apoio), Nível 2 (exigindo apoio substancial), Nível 3 (exigindo apoio muito substancial). Características pedagógicas: dificuldade com linguagem figurada, necessidade de rotina previsível, hiperfoco em interesses específicos, sensibilidade sensorial, dificuldade com teoria da mente." },
  { source: "DSM-5", category: "diagnostico", title: "TDAH — Transtorno do Déficit de Atenção com Hiperatividade (DSM-5 314.01 / CID-11 6A05)", content: "Padrão persistente de desatenção e/ou hiperatividade-impulsividade que interfere no funcionamento ou no desenvolvimento. Apresentações: predominantemente desatento, predominantemente hiperativo-impulsivo, ou combinado. Características pedagógicas: dificuldade em manter atenção sustentada, distração fácil por estímulos irrelevantes, dificuldade em organizar tarefas, inquietação motora, impulsividade em respostas, dificuldade em esperar a vez." },
  { source: "DSM-5", category: "diagnostico", title: "Dislexia — Transtorno Específico da Aprendizagem com Prejuízo na Leitura (DSM-5 315.0 / CID-11 6A03.0)", content: "Dificuldade na precisão da leitura de palavras, velocidade ou fluência da leitura e compreensão da leitura. O desempenho é substancialmente abaixo do esperado para a idade cronológica. Não é explicado por deficiência intelectual, acuidade visual ou auditiva não corrigida, ou instrução inadequada. Características pedagógicas: troca ou inversão de letras, leitura lenta e imprecisa, dificuldade em decodificação fonológica, compreensão de texto prejudicada pela dificuldade de decodificação." },
  { source: "DSM-5", category: "diagnostico", title: "Discalculia — Transtorno Específico da Aprendizagem com Prejuízo na Matemática (DSM-5 315.1 / CID-11 6A03.1)", content: "Dificuldade no senso numérico, memorização de fatos aritméticos, cálculo preciso ou fluente, e raciocínio matemático preciso. Características pedagógicas: dificuldade em compreender quantidades e relações numéricas, problemas com o sistema posicional, dificuldade em memorizar tabuada, confusão com sinais operacionais, dificuldade em resolver problemas com múltiplas etapas." },
  { source: "DSM-5", category: "diagnostico", title: "Deficiência Intelectual (DSM-5 317-319 / CID-11 6A00)", content: "Déficits em funções intelectuais e adaptativas confirmados tanto por avaliação clínica quanto por testes padronizados. Graus: leve (317), moderado (318.0), grave (318.1), profundo (318.2). Características pedagógicas: aprendizagem mais lenta, necessidade de repetição e concretude, dificuldade com abstração, melhor desempenho com materiais manipulativos, necessidade de objetivos individualizados e avaliação processual." },
  { source: "CID-11", category: "diagnostico", title: "TDL — Transtorno do Desenvolvimento da Linguagem (CID-11 6A01)", content: "Dificuldades persistentes na aquisição, compreensão, produção ou uso da linguagem (falada ou escrita) que resultam em habilidades linguísticas abaixo do esperado para a idade. Não é explicado por déficit auditivo, intelectual ou condição neurológica. Características pedagógicas: vocabulário limitado, dificuldade em formar frases complexas, compreensão literal, dificuldade em narrativas, necessidade de suporte visual e tempo extra para respostas." },
  { source: "CID-11", category: "diagnostico", title: "Altas Habilidades / Superdotação (Res. CNE/CEB 2/2001)", content: "Pessoa com notável desempenho e/ou elevada potencialidade em qualquer dos aspectos: capacidade intelectual geral, aptidão acadêmica específica, pensamento criativo, capacidade de liderança, talento especial para artes, capacidade psicomotora. Não é um diagnóstico DSM-5/CID-11, mas é reconhecida pela legislação brasileira como público-alvo da educação especial. Características pedagógicas: aprendizagem rápida, curiosidade intensa, pensamento divergente, perfeccionismo, pode apresentar desinteresse em atividades repetitivas, risco de subdesempenho se não estimulado." },
];

async function seed() {
  console.log("🌱 Iniciando seed da base RAG...\n");

  const allDocs = [
    ...BNCC_MATEMATICA.map(d => ({ source: "BNCC", category: "habilidade", ...d })),
    ...BNCC_CIENCIAS.map(d => ({ source: "BNCC", category: "habilidade", ...d })),
    ...BNCC_LINGUA_PORTUGUESA.map(d => ({ source: "BNCC", category: "habilidade", ...d })),
    ...LEGISLACAO,
    ...DSM5_CID11,
  ];

  const BATCH_SIZE = 5;
  for (let i = 0; i < allDocs.length; i += BATCH_SIZE) {
    const batch = allDocs.slice(i, i + BATCH_SIZE);
    console.log(`  📄 Indexando batch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(allDocs.length / BATCH_SIZE)} (${batch.length} docs)...`);
    await indexDocumentsBatch(batch);
  }

  console.log(`\n✅ Seed concluído! ${allDocs.length} documentos indexados.`);
  console.log(`   BNCC: ${BNCC_MATEMATICA.length + BNCC_CIENCIAS.length + BNCC_LINGUA_PORTUGUESA.length} habilidades`);
  console.log(`   Legislação: ${LEGISLACAO.length} artigos`);
  console.log(`   DSM-5/CID-11: ${DSM5_CID11.length} perfis`);
}

seed().catch(err => {
  console.error("❌ Erro no seed:", err.message);
  process.exit(1);
});
